baseurl = "http://critical-mass-sternfahrt.de/"
languageCode = "de-de"
title = "Critical Mass Sternfahrt"
theme = "critical-mass-sternfahrt-theme"

[params]
  author = "Critical Mass Netzwerk in der Metropolregion Stuttgart"
  slogan = "You never ride alone!"
  github = "criticalmasssternfahrt"
  twitter = "CriticalMass_S"
  facebook = "criticalmassstuttgart"
